name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/git/db/
          ~/.cargo/registry/cache/
          ~/.cargo/registry/index/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: install
      run: cargo install --quiet cargo-tarpaulin
      continue-on-error: true
    
    - name: test
      run: cargo tarpaulin --out xml
    
    - name: codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
